logging:
  root:
    level: DEBUG

dossier.store:
  feature_indexes: ['phone', 'email', 'bowNP_sip', 'region', 'image_url']

dossier.web:
  index_scan_make_fc:
    tfidf_path: /memex-100000.tfidf

kvlayer:
  app_name: dossierstack
  namespace: demo
  storage_type: filestorage
  filename: /kvlayer/demo.db
  storage_addresses: []
